imports:
    - php
checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
            - phpunit/phpunit
            - fzaninotto/faker

tools:
    php_sim: false
    php_cpd: false
filter:
    excluded_paths:
        - config/*
        - docs/*
        - tests/*
        - vendor/*
